eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
server:
  port: 8872
  a: 1
spring:
  application:
    name: service-a
  rabbitmq:
    host: localhost
    port: 5672  
